### ISSUE TITLE
Last version (5) says "wallpaperOverlaySetting is undefined" in GNOME 42.2

### ISSUE THREAD

**Issue by KierPrev** [rishuinfinity/WallpaperSwitcher#7]
I will use version 4, for the moment

**Comment by rishuinfinity** [comment]
Hi thanks for the heads up, I am currently on Gnome 42.1 and I had tested the extension for this device.
Even though this error is shown in prefs window, I believe the extension should work without problems anyways. 

Tho, I'd like to ask you to please help me with some info on the bug so that I can fix it. Can you please
* Tell me if you had WallpaperOverlay installed?
* Show me what was logged in ~/.local/var/log/WallpaperSwitcher.log 

Thanks again for your help

**Comment by KierPrev** [comment]
Thanks!

I don't have WallpaperOverlay installed.
And there's no log on that path.

**Comment by rishuinfinity** [comment]
ok, then the new version wont have any issues running. You can use it without any worries, just take that message as a small warning. In the meantime I'll try to recreate the problem and solve this issue.

**Comment by KierPrev** [comment]
The message disappeared after a restart. Strange.
So, maybe you don't have to debug anything. 

Thanks!
